### PR TITLE
Internationalization

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will introduce the internationalization (i18n) feature.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
merging it as I need to check the deployed result

**Comment by gab3d** [comment]
Hi @shun-iwasawa 
What is it needed (from a technical standpoint) to have a working Spanish localization of the manual? 🤔

**Comment by gab3d** [comment]
...also, is it technically possible to have localized screenshots?

**Comment by Savraska2** [comment]
@gab3d I can generate translation .po files into Spanish so that you can translate directly on Githab or in any way convenient for you. For various reasons, I cannot promise that I will be able to update the  .po files in a timely manner if the .rst source files change. This is not difficult, but there may not be a computer and an Internet connection in the vicinity. If you have questions about the Sphinx, I will try to help you.

**Comment by Savraska2** [comment]
The question of localized screenshots for Russian translation is also relevant. I don’t know what I’m going to do or write the name in brackets: Archivo (File) or make a folder for localized screenshots.

**Comment by gab3d** [comment]
@Savraska2 thank you!

> For various reasons, I cannot promise that I will be able to update the .po files in a timely manner if the .rst source files change. This is not difficult

I see... no problem. If it's not a super complicated procedure, perhaps I can keep them updated.
Could you give me some hits about it?

**Comment by Savraska2** [comment]
Off course, I use `make gettext` for generate .pot files
`sphinx-intl update -p build/gettext -l es` for generate .po and
`make SPHINXOPTS="-D language='es'" html` for generate .mo files and html. All actions are performed in the root folder opentoonz_docs repo.

**Comment by Savraska2** [comment]
You first need to install a [Python](https://www.python.org/downloads/windows/), enter in cmd.exe `pip sphinx`, `pip sphinx-intl`, `pip sphinx_rtd_theme`, `pip sphinx-autobuild`.

**Comment by gab3d** [comment]
@Savraska2 
Thank you!

..to be honest I still can't exactly figure out how to execute something y the *opentoonz_docs repo*, you mean my local copy of it, right? 🤔 
I'll give it a try. 👍 

On other related things, I've started to translate some of the sections and I've found that in the *using_ffmpeg_with_opentoonz.po* file there are some strings lost towards the end of it (linux install instructions).

**Comment by Savraska2** [comment]
You are right, you should run these commands in your local copy.

I could not find the missing lines in the _using_ffmpeg_with_opentoonz.po_ file, everything is completely translated.

**Comment by gab3d** [comment]
Ah... now I see whats happening:
The strings:
- "Navigate to the **Import/Export** category; at the top you will see a box with the text **FFmpeg path**." 
- Insert the path **/usr/bin**.
- Restart OpenToonz.

are duplicated and the translation is being reused from other strings above.
That's why I detected that there was something missing in the po file.
Sorry!

**Comment by Savraska2** [comment]
Im completely forgot about this Sphinx feature)

Perhaps the following trick will be useful to you: I rename the _.rst_ file to _.txt_, translate it as a document in Google translator, and then copy the translation to a _.po_ file. It makes work a little easier.

**Comment by gab3d** [comment]
Thanks for the tip!
Anyways, I think for now I'm well served with my current workflow that involves just using Poedit and translating "by hand".
I think by the end of the day I get a better translation and not that slower, if I take into consideration the revision efforts that I would have to undertake if I let Google do it "as well as it does" hehe. 😉

**Pull request merged**
