### PR TITLE
start i18n es

### PR DESCRIPTION
**Pull request by Savraska2**

### CODE REVIEW

**Comment by gab3d** [comment]
is there anything left to be done, so I can see the Spanish version live in the language menu of the manual?
because I still don't... 🤔 
thanks!

Sin título

**Comment by Savraska2** [comment]
Great! That works fine.)

spanish

For adding spanish language in web manual needed some settings.
@shun-iwasawa Please add spanish language support. Thank you!

**Comment by gab3d** [comment]
Woohoo!!
Great to know!

**Comment by shun-iwasawa** [comment]
Added Spanish translation option to the manual. Thank you so much !

**Pull request merged**
