### PR TITLE
Replace all Toonz Harlequin 7.1 images in Applying Special FX section

### PR DESCRIPTION
**Pull request by WolfInABowl**
All old images are replaced with new images captured from OT rather than TH7.1
One additional image has been added for Pinned Texture in order to show its other tab

This is my first time with RST, let me know if I've done something wrong

As OT's UI has changed from TH7.1, the references to the colors of the nodes needs to be updated, as you can see in the screen below ('Displayed as a **yellow** node'). This will be included as part of a series of modifications I will make to the Docs soon.

Here's a quick screen to show how one looks on the page:
image

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Thank you @WolfInABowl for replacing images by OT's ones!

I'll be happy to assign you a collaborator access to this repository so that you can modify it easily in the future.
Your cooperation on this project is greatly appreciated.

**Comment by shun-iwasawa** [comment]
@WolfInABowl 
To accept the invitation to the collaborators, please access to https://github.com/opentoonz/opentoonz_docs/invitations . Thanks!

**Comment by gab3d** [comment]
Wow, thanks @WolfInABowl !!

I'm particularly happy about this one,  as I was just about to start doing it myself when I returned from my vacations next week.
So, I can happily delete that task from my calendar now. 😅

**Comment by Savraska2** [comment]
Thank you for contribution @WolfInABowl !
A pdf document cannot contain gif illustrations, so I will convert them to png if no one is against.
screenshot

**Comment by WolfInABowl** [comment]
Sure, that sounds great

**Pull request merged**
