### PR TITLE
More info about Linux

### PR DESCRIPTION
**Pull request by Savraska2**

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Thanks for the update @Savraska2 !

Assuming you know the individuals who supply content at the sites linked to perhaps you can work with them to update their content.  

Two things that don't paint those links in the best of light is an encountered 404 missing page (via secondary link) and the immediate requests for financial assistance upon arrival via one of the links.

If it's not clear to you what these are it might be bet simply to remove the links.
In any case, recommend reviewing those areas of interest to ensure those links within documentation can be maintained.

**Comment by Savraska2** [comment]
> Assuming you know the individuals who supply content at the sites linked to perhaps you can work with them to update their content.
> This is not the case; I have no relation to any of the resources to which links are given, im just enthusiast and home user OpenToonz
> Two things that don't paint those links in the best of light is an encountered 404 missing page (via secondary link) and the immediate requests for financial assistance upon arrival via one of the links. 
> I did not quite understand exactly which links you have in mind, the only link that a request for donation comes out of is a link to Morevna Project, added not by me. Аll other links lead to famous open source repositories, such as the GitHub, Aur or deb-multimedia. All my links open correctly, without errors. 
Ps sorry for my bad english, Im not native english speaker)

**Comment by Savraska2** [comment]
@RodneyBaker In the event that links lead to inappropriate content not related to OpenToonz, I will immediately remove them.

**Comment by RodneyBaker** [comment]
Thanks.  I should have posted the specific links but my primary and immediate concern was that we not tarnish the ability to get Linux distributions out into the public eye.

The two links in question are not entirely prominent... they are found at the bottom of the page.

The first thing that catches the eye is the link "AUR".
It's not clear what that link is, what it means or where it goes but we might conclude it links to the Arch Linux download for OpenToonz.  It... almost... does.

Where we travel to is the arch linux site but the first link we see (besides the menu links at the top of the page) links to a 404 missing page link:

https://aur.archlinux.org/opentoonz.git

That's the main issue of that linkage.
I'll add another post to outine the other.

**Comment by RodneyBaker** [comment]
The second area of interest is immediately above the Arch linux link in a sentence that reads:

"For more information visit repository website ."

The link in that sentence is 'respository website' and appears to inproperly link to:

http://deb-multimedia.org/

This might not be in error per say but does have an additional and unfortunate notice from 2007 at the top of the page which states:

> What's up doc ?
> 17/08/2007 :
> I think you have noticed the Google Ads. I need that to pay the huge amount of bandwidth.

This also isn't in and of itself a bad thing but is an unfortunate thing to come across when simply looking to download a copy of Opentoonz for Debian GNU/Linux and potentially puts that distribution in a bad light.

This all may seem trivial and perhaps is but I am concerned with keeping these Linux distributions in the absolute best possible light.

Thanks for your consideration.

**Comment by Savraska2** [comment]
>The first thing that catches the eye is the link "AUR".
It's not clear what that link is, what it means or where it goes but we might conclude it links to the Arch Linux download for OpenToonz. It... almost... does.

AUR is is a repository of programs for Arch Linux. I understand that it puzzled you). For Arch and Gentoo there will soon be a detailed description of the installation. Addition "Linux" (or GNU/Linux) just a part of name these OSes.

>Where we travel to is the arch linux site but the first link we see (besides the menu links at the top of the page) links to a 404 missing page link: https://aur.archlinux.org/opentoonz.git

The text does not contain a link to https://aur.archlinux.org/opentoonz.git, which really ends with a 404 error, but https://aur.archlinux.org/packages/opentoonz, which works. 

>This might not be in error per say but does have an additional and unfortunate notice from 2007 at the top of the page which states: What's up doc ?
17/08/2007 :
I think you have noticed the Google Ads. I need that to pay the huge amount of bandwidth.

Do not let this be misleading, the site is working properly)  Perhaps I will make the description in more detail, and delete the link tomorrow. Thank you for your concern about the reputation of Linux systems.)

**Comment by Savraska2** [comment]
Oh, you right, aur repo not avalaible and link in the docs will be removed.

**Pull request merged**
