### PR TITLE
Convert gif from Special FX to png

### PR DESCRIPTION
**Pull request by Savraska2**
Converting because it is impossible to include gif files in the pdf document.

### CODE REVIEW

**Comment by Savraska2** [comment]
Folders "applying_special_fx" and "sfx" were merged. All pictures for Special FX chapters are in the same folder.

**Comment by WolfInABowl** [comment]
There seem to be some images in the Blur section that exhibit some misalignment from the png conversion
image

**Comment by Savraska2** [comment]
You're right. I'll trying fix it.

**Comment by Savraska2** [comment]
Fixed. So many damaged files, that's strange. I used `convert` utility.

**Pull request merged**
